version: "3.3"

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 4406:3306
    volumes:
      - dbdata:/var/lib/mysql
      - ./dbdata:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wpdb

  wordpress:
    image: wordpress:latest
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./wp-content/plugins/marram-blocks:/var/www/html/wp-content/plugins/marram-blocks
      - ./wp-content/themes/marram:/var/www/html/wp-content/themes/marram
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_HOME', 'http://localhost:8080' );
        define( 'WP_SITEURL', 'http://localhost:8080' );

volumes:
  dbdata:
