files:
  ignore:
    - node_modules/**
rules:
  attribute-quotes:
    - 2
    - include: true
  bem-depth:
    - 2
    - max-depth: 2
  border-zero:
    - 2
    - convention: none
  class-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedbem
  clean-import-paths:
    - 2
    - leading-underscore: false
      filename-extension: false
  declarations-before-nesting: 2
  empty-args:
    - 2
    - include: false
  empty-line-between-blocks:
    - 2
    - include: true
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 2
    - include: true
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  hex-length:
    - 2
    - style: short
  hex-notation:
    - 2
    - style: lowercase
  id-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  indentation:
    - 2
    - size: tab
  leading-zero:
    - 2
    - include: false
  max-file-line-count:
    - 1
    - length: 500
  max-line-length:
    - 1
    - length: 80
  mixin-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  mixins-before-declarations:
    - 2
    - exclude:
        - breakpoint
        - number-of-children
        - hack
        - admin-bar
        - tags
  nesting-depth:
    - 2
    - max-depth: 3
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 0
  no-debug: 1
  no-disallowed-properties: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 1
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 0
  no-misspelled-properties:
    - 2
    - 'extra-properties':
      - 'composes'
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: true
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 1
  no-universal-selectors: 2
  no-url-domains: 0
  no-url-protocols:
    - 1
    - allow-protocol-relative-urls: true
  no-vendor-prefixes:
    - 2
    - ignore-non-standard: true
  no-warn: 1
  one-declaration-per-line: 2
  placeholder-in-extend: 0
  placeholder-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  property-sort-order:
    - 2
    - order: alphabetical
  pseudo-element: 0
  quotes:
    - 2
    - style: double
  shorthand-values: 2
  single-line-per-selector: 1
  space-after-bang:
    - 2
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-after-comma:
    - 2
    - include: true
  space-around-operator:
    - 2
    - include: true
  space-before-bang:
    - 2
    - include: true
  space-before-colon:
    - 2
    - include: false
  space-between-parens:
    - 2
    - include: false
  url-quotes: 2
  variable-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  zero-unit:
    - 2
    - include: false
